FROM ${BASEIMAGE} AS build
WORKDIR /build
COPY out/ .
RUN npm ci --unsafe-perms --production --registry=${NPM_REGISTRY}
# --loglevel silly
# pull base image
FROM ${BASEIMAGE_SLIM}
WORKDIR /app
COPY . .
COPY --from=build /build/node_modules ./node_modules
RUN apk add --update file imagemagick

# define default command
CMD ["node", "--inspect=0.0.0.0:9229", "app.js"]

# expose ports
EXPOSE 3020
EXPOSE 9229

